CREATE DATABASE LibraryDB
GO
USE LibraryDB
GO
use master

CREATE TABLE BOOKS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NAMEBOOK NVARCHAR(100) NOT NULL,
    AUTHOR NVARCHAR(100),
    CATEGORY NVARCHAR(50),
    STATUSS BIT DEFAULT 0
);
GO
CREATE TABLE USERS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NAMEUSER NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);
GO
CREATE TABLE BORROW (
    ID INT PRIMARY KEY IDENTITY(1,1),
    USER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    BORROW_DATE DATE DEFAULT GETDATE(),
    RETURN_DATE DATE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);

ALTER TABLE BOOKS
ADD CONSTRAINT DF_BOOKS_STATUSS DEFAULT 1 FOR STATUS;


ALTER TABLE USERS
ADD CONSTRAINT PK_USERNAME UNIQUE (USERNAME);


SELECT *FROM BOOKS
SELECT *FROM USERS 
SELECT *FROM BORROW

ALTER TABLE BOOKS 
ADD STATUS BIT DEFAULT 1

CREATE TABLE VERIFY (
    OTP VARCHAR(255),
    USERNAME VARCHAR(255)

)

UPDATE BORROW SET RETURN_DATE =NULL
UPDATE BOOKS SET STATUS = 0 WHERE ID = 20
-- ALTER TABLE USERS 
-- ADD USERNAME VARCHAR(255) ,
--  PASSWORD VARCHAR(255),
--  ROLE VARCHAR(50) DEFAULT 'USER'
-- UPDATE USERS SET ROLE = 'ADMIN' WHERE ID = 8
-- UPDATE BOOKS SET STATUSS = 1 WHERE ID IN (5, 7);
