CREATE DATABASE LibraryDB
GO
USE LibraryDB
GO

CREATE TABLE BOOKS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NAMEBOOK NVARCHAR(100) NOT NULL,
    AUTHOR NVARCHAR(100),
    CATEGORY NVARCHAR(50),
    STATUS BIT DEFAULT 1
);
GO
CREATE TABLE USERS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NAMEUSER NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255), 
    ROLE VARCHAR(50 DEFAULT 'USER'
);
GO
CREATE TABLE BORROW (
    ID INT PRIMARY KEY IDENTITY(1,1),
    USER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    BORROW_DATE DATE DEFAULT GETDATE(),
    RETURN_DATE DATE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);


SELECT *FROM BOOKS
SELECT *FROM USERS 
SELECT *FROM BORROW


